api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "https://github.com/kubeflow/manifests"
  args: "apps/tensorboard/tensorboards-web-app/upstream/overlays/istio"
  type: kustomize
  wait: true
- path: "https://github.com/kubeflow/manifests"
  args: "apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow"
  type: kustomize
  wait: true
# - path: post
#   args: "kubectl patch svc katib-ui  -n kubeflow -p $'spec:\n type: LoadBalancer'"
#   type: shell