apiVersion: v1
kind: Service
metadata:
  name: rubrix
spec:
  type: NodePort
  ports:
    - port: 6900
      targetPort: 80
      nodePort: 30690
      protocol: TCP
      name: http
  selector:
    app: rubrix