api: k3ai.in/v1alpha1
kind: Infra
metadata:
  name: civo
  desc: "The first cloud native service provider powered only by Kubernetes."
  tag: cloud
  version: latest
  status: "In Development"
resources:
- base/
