api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "https://github.com/kubeflow/manifests"
  args: "apps/pipeline/upstream/env/platform-agnostic-multi-user-pns"
  type: kustomize
  wait: true
# - path: post
#   args: "kubectl patch vs ml-pipeline-ui  -n kubeflow -p $'spec:\n host: LoadBalancer'"
#   type: shell