api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "apply -f https://raw.githubusercontent.com/k3ai/plugins/main/common/postgresql/overlays/configmap.yaml"
  args: ""
  type: kubectl
  wait: true
- path: "apply -f https://raw.githubusercontent.com/k3ai/plugins/main/common/postgresql/overlays/pv.yaml"
  args: ""
  type: kubectl
  wait: true
- path: "apply -f https://raw.githubusercontent.com/k3ai/plugins/main/common/postgresql/overlays/secret.yaml"
  args: ""
  type: kubectl
  wait: true
- path: "apply -f https://raw.githubusercontent.com/k3ai/plugins/main/common/postgresql/overlays/statefulset.yaml"
  args: ""
  type: kubectl
  wait: true
- path: "apply -f https://raw.githubusercontent.com/k3ai/plugins/main/common/postgresql/overlays/service.yaml"
  args: ""
  type: kubectl
  wait: true


