api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml"
  args: ""
  type: kubectl
  wait: true
- path: "wait pods -l application-crd-id=kubeflow-pipelines -n tekton-pipelines --for condition=Ready --timeout=1800s"
  args: ""
  type: kubectl
  wait: true
- path: "patch svc ml-pipeline-ui -n tekton-pipelines --type='json' -p '[{\"op\":\"replace\",\"path\":\"/spec/type\",\"value\":\"NodePort\"},{\"op\":\"replace\",\"path\":\"/spec/ports/0/nodePort\",\"value\":30901}]'"
  type: kubectl
