api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml"
  args: ""
  type: kubectl
  wait: true
- path: "patch cm feature-flags -n tekton-pipelines -p '{\"data\":{\"enable-custom-tasks\": \"true\", \"enable-api-fields\": \"alpha\"}}'"
  type: kubectl
- path: "apply --selector kubeflow/crd-install=true -f https://raw.githubusercontent.com/kubeflow/kfp-tekton/master/install/v1.0.0/kfp-tekton.yaml "
  type: kubectl
- path: "apply -f https://raw.githubusercontent.com/kubeflow/kfp-tekton/master/install/v1.0.0/kfp-tekton.yaml"
  type: kubectl
- path: "wait pods -l application-crd-id=kubeflow-pipelines -n kubeflow --for condition=Ready --timeout=1800s"
  args: ""
  type: kubectl
  wait: true
- path: "patch svc ml-pipeline-ui -n kubeflow --type='json' -p '[{\"op\":\"replace\",\"path\":\"/spec/type\",\"value\":\"NodePort\"},{\"op\":\"replace\",\"path\":\"/spec/ports/0/nodePort\",\"value\":30901}]'"
  type: kubectl
