api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "https://github.com/kubeflow/manifests"
  args: "apps/pipeline/upstream/cluster-scoped-resources"
  type: kustomize
  wait: true
- path: "wait crd/applications.app.k8s.io --for condition=established --timeout=60s"
  args: ""
  type: kubectl
  wait: true
- path: "https://github.com/kubeflow/manifests"
  args: "apps/pipeline/upstream/env/platform-agnostic-pns"
  type: kustomize
  wait: true
- path: "wait pods -l application-crd-id=kubeflow-pipelines -n kubeflow --for condition=Ready --timeout=1800s"
  args: ""
  type: kubectl
  wait: true
# - path: post
#   args: "kubectl patch vs ml-pipeline-ui  -n kubeflow -p $'spec:\n host: LoadBalancer'"
#   type: shell