api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "repo add apache-airflow https://airflow.apache.org"
  args: ""
  type: helm
  wait: true
- path: "create namespace airflow"
  args: ""
  type: kubectl
  wait: true
- path: "install airflow apache-airflow/airflow --namespace airflow --set web.service.type=NodePort --set web.service.nodePort=30200"
  args: ""
  type: helm
  wait: true
  remove: ""
