api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "repo add apache-airflow https://airflow.apache.org"
  args: ""
  type: helm
  wait: true
- path: "create namespace airflow-workloads"
  args: ""
  type: kubectl
  wait: true
- path: "helm install airflow apache-airflow/airflow --namespace airflow"
  args: ""
  type: helm
  wait: true
  remove: ""