api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "repo add apache-airflow https://airflow.apache.org"
  args: ""
  type: helm
  wait: true
- path: "create namespace airflow"
  args: ""
  type: kubectl
  wait: true
- path: "install airflow apache-airflow/airflow --namespace airflow {{extra}}"
  args: ""
  type: helm
  wait: true
  remove: ""
- path: "patch svc kairflow-webserver -n airflow --type='json' -p '[{\"op\":\"replace\",\"path\":\"/spec/type\",\"value\":\"NodePort\"},{\"op\":\"replace\",\"path\":\"/spec/ports/0/nodePort\",\"value\":30800}]'"
  type: kubectl"

