apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  namespace: jupyter
spec:
  selector:
    name: jupyterlab
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
  type: ClusterIP
