api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "https://github.com/kubeflow/manifests"
  args: "common/knative/knative-eventing/base"
  type: kustomize
  wait: true
- path: "https://github.com/kubeflow/manifests"
  args: "common/knative/knative-serving/base"
  type: kustomize
  wait: true
- path: "https://github.com/kubeflow/manifests"
  args: "common/istio-1-9/cluster-local-gateway/base"
  type: kustomize
  wait: true
- path: "https://github.com/kubeflow/manifests"
  args: "common/knative/knative-serving/overlays/gateways"
  type: kustomize
  wait: true


