api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "https://github.com/kubeflow/manifests"
  args: "common/kubeflow-namespace/base "
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/knative/knative-serving/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/istio-1-9/cluster-local-gateway/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/istio-1-9/kubeflow-istio-resources/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/knative/knative-eventing/base"
  type: kustomize
  wait: false

