api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "https://github.com/kubeflow/manifests"
  args: "common/kubeflow-namespace/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/kubeflow-roles/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/cert-manager/cert-manager/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/cert-manager/kubeflow-issuer/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/istio-1-9/istio-crds/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/istio-1-9/istio-namespace/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/istio-1-9/istio-install/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/istio-1-9/kubeflow-istio-resources/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "apps/katib/upstream/installs/katib-with-kubeflow"
  type: kustomize
  wait: false
- path: post
  args: "kubectl patch svc katib-ui  -n kubeflow -p $'spec:\n type: LoadBalancer'"
  type: shell