api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "create ns kubeflow"
  args: ""
  type: kubectl
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "apps/katib/upstream/installs/katib-with-kubeflow"
  type: kustomize
  wait: true
- path: "delete svc katib-ui -n kubeflow"
  type: kubectl
- path: "expose deployment katib-ui --type=NodePort --target-port=8080  --port=80 -n kubeflow"
  type: kubectl