api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "create ns kubeflow"
  args: ""
  type: kubectl
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "apps/katib/upstream/installs/katib-with-kubeflow"
  type: kustomize
  wait: true
- path: post
  args: "kubectl patch svc katib-ui  -n kubeflow -p $'spec:\n type: LoadBalancer'"
  type: shell