api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "https://github.com/kubeflow/manifests"
  args: "apps/katib/upstream/installs/katib-with-kubeflow"
  type: kustomize
  wait: true
- path: "patch svc katib-ui -n kubeflow --type='json' -p '[{\"op\":\"replace\",\"path\":\"/spec/type\",\"value\":\"NodePort\"},{\"op\":\"replace\",\"path\":\"/spec/ports/0/nodePort\",\"value\":30500}]'"
  type: kubectl
# - path: "get svc airflow-webserver -n airflow -o=jsonpath='{.spec.ports[?(@.port==8080)].nodePort}'"
#   type: kubectl
