api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "apply -f https://raw.githubusercontent.com/k3ai/plugins/main/apps/mlflow/overlays/deployment.yaml"
  args: ""
  type: kubectl
  wait: true
- path: "apply -f https://raw.githubusercontent.com/k3ai/plugins/main/apps/mlflow/overlays/service.yaml"
  args: ""
  type: kubectl
  wait: true
