api: k3ai.in/v1alpha1
kind: Infra

resources:
- path: " curl -Lo /tmp/tce-linux-amd64-v0.9.1.tar.gz https://github.com/vmware-tanzu/community-edition/releases/download/v0.9.1/tce-linux-amd64-v0.9.1.tar.gz"
  args: ""
  kubeconfig: ""
  type: shell
  wait: true
- path: "tar xzvf /tmp/tce-linux-amd64-v0.9.1.tar.gz && cd /tmp && tce-linux-amd64-v0.9.1/install.sh"
  args: ""
  kubeconfig: ""
  type: shell
  wait: false
- path: "./tmp/tce-linux-amd64-v0.9.1/install.sh"
  args: ""
  kubeconfig: ""
  type: shell
  wait: false
- path: "tanzu standalone-cluster create -i docker {{NAME}}" 
  args: ""
  kubeconfig: ""
  wait: true
  remove: "tanzu cluster delete {{name}}"
