api: k3ai.in/v1alpha1
kind: Infra

resources:
- path: " curl -H 'Accept: application/vnd.github.v3.raw' -L https://api.github.com/repos/vmware-tanzu/community-edition/contents/hack/get-tce-release.sh | bash -s {{RELEASE-VERSION}} {{RELEASE-OS-DISTRIBUTION}}"
  args: ""
  kubeconfig: ""
  type: shell
  wait: true
- path: "tar xzvf {{DOWNLOAD-DIR}}/tce-{{RELEASE-OS-DISTRIBUTION}}-amd64-{{RELEASE-VERSION}}.tar.gz && {{DOWNLOAD-DIR}}/tce-linux-amd64-{{RELEASE-VERSION}}/install.sh"
  args: ""
  kubeconfig: ""
  type: shell
  wait: false
- path: "tanzu standalone-cluster create -i docker {{NAME}}" 
  args: ""
  kubeconfig: ""
  wait: true
  remove: "tanzu cluster delete {{name}}"
