api: k3ai.in/v1alpha1
kind: Infra

resources:
- path: " curl -Lo tce-linux-amd64-v0.9.1.tar.gz https://github.com/vmware-tanzu/community-edition/releases/download/v0.9.1/tce-linux-amd64-v0.9.1.tar.gz"
  args: ""
  kubeconfig: ""
  type: shell
  wait: true
- path: "tar -xvzf tce-linux-amd64-v0.9.1.tar.gz"
  args: ""
  kubeconfig: ""
  type: shell
  wait: false
- path: "./tce-linux-amd64-v0.9.1/install.sh"
  args: ""
  kubeconfig: ""
  type: shell
  wait: false
- path: "tanzu standalone-cluster create -i {{extras}} {{name}}" 
  args: "docker"
  kubeconfig: ""
  type: shell
  wait: true
  remove: "tanzu standalone-cluster delete {{name}}"
- path: "apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml" 
  args: ""
  kubeconfig: ""
  type: kubectl
  wait: true
- path: "patch storageclass local-path -p '{\"metadata\": {\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"true\"}}}'" 
  args: ""
  kubeconfig: ""
  type: kubectl
  wait: true
