api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml"
  args: ""
  type: kubectl
  wait: true
- path: "patch svc argo-server -n argo --type='json' -p '[{\"op\":\"replace\",\"path\":\"/spec/type\",\"value\":\"NodePort\"},{\"op\":\"replace\",\"path\":\"/spec/ports/0/nodePort\",\"value\":32746}]'"
  type: kubectl