api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "https://github.com/kubeflow/manifests"
  args: "common/cert-manager/cert-manager/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/cert-manager/kubeflow-issuer/base"
  type: kustomize
  wait: true

