api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "apply -k github.com/kubeflow/training-operator/manifests/overlays/standalone?"
  args: "ref=v1.3.0"
  type: kubectl
  wait: true
# - path: post
#   args: "kubectl patch svc katib-ui  -n kubeflow -p $'spec:\n type: LoadBalancer'"
#   type: shell