api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "https://github.com/kubeflow/manifests"
  args: "common/istio-1-9/istio-crds/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/istio-1-9/istio-namespace/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/istio-1-9/istio-install/base"
  type: kustomize
  wait: false
- path: "https://github.com/kubeflow/manifests"
  args: "common/istio-1-9/kubeflow-istio-resources/base"
  type: kustomize
  wait: true
