api: k3ai.in/v1alpha1
kind: Application

resources:
- path: "https://github.com/kubeflow/manifests"
  args: "apps/pipeline/upstream/cluster-scoped-resources"
  type: kustomize
  wait: true
- path: "wait crd/applications.app.k8s.io --for condition=established --timeout=60s"
  args: ""
  type: kubectl
  wait: true
- path: "https://github.com/kubeflow/manifests"
  args: "apps/pipeline/upstream/env/platform-agnostic-pns"
  type: kustomize
  wait: true
- path: "wait pods -l application-crd-id=kubeflow-pipelines -n kubeflow --for condition=Ready --timeout=1800s"
  args: ""
  type: kubectl
  wait: true
- path: "patch svc ml-pipeline-ui -n kubeflow --type='json' -p '[{\"op\":\"replace\",\"path\":\"/spec/type\",\"value\":\"NodePort\"},{\"op\":\"replace\",\"path\":\"/spec/ports/0/nodePort\",\"value\":30900}]'"
  type: kubectl

