api: k3ai.in/v1alpha1
kind: Infra

resources:
- path: "curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --disable traefik"
  args: ""
  kubeconfig: "/etc/rancher/k3s/k3s.yaml"
  type: shell
  wait: true

